### ISSUE TITLE
Doesn't work with Python 3.8

### ISSUE THREAD

**Issue by vincent-dm** [trek10inc/awsume#112]
After Homebrew upgraded Python from `3.7` to `3.8`, `awsume` stopped working:
```
/usr/local/bin/awsume:5: /usr/local/bin/awsumepy: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
```

Presumably because the `awsumepy` script contains a hashbang `#!/usr/local/opt/python/bin/python3.7`, which effectively ties it to Python 3.7.

When I create a symlink to Python 3.8, it also fails:
```
Traceback (most recent call last):
  File "/usr/local/bin/awsumepy", line 5, in <module>
    from awsume.awsumepy.main import main
ModuleNotFoundError: No module named 'awsume'

```

Presumably, awsume is not compatible with Python 3.8. Ideally it can be made compatible, so it can rely on a less specific version (e.g. `#!/usr/bin/env python3`).

**Comment by mbarneyjr** [comment]
The `#!` isn't awsume-specific. When installing python via brew, `pip install`ing packages with console entry points will create a file that has a version-specific `#!` line. This seems like a homebrew issue, I don't know how much guidance I can provide with that.

FWIW, I strongly recommend installing python command-line tools with [pipx](https://pipxproject.github.io/pipx/), that would help prevent issues like this since each package is installed into a separate virtualenv

**Comment by vincent-dm** [comment]
Thank you for the explanation. And also for making the awesome awsume!

**Comment by nmarchini** [comment]
What was the fix for this in the end?

**Comment by mbarneyjr** [comment]
I'm not sure what exactly their solution was, but I do highly recommend the use of [pipx](https://pipxproject.github.io/pipx/) for installing awsume. It should prevent these kinds of issues with brew since it installs everything into an isolated virtualenv (assuming you didn't try to `pip install awsume` globally)

**Comment by ramonrovirosa** [comment]
For me I had a similiar issue and a simple
`pipx uninstall awsume`
and then
`pipx install awsume`
fixed the issue.

I assume trying a `pip uninstall awsume` and `pip install awsume` might fix it.
