### ISSUE TITLE
autoawsume in the background or not?

### ISSUE THREAD

**Issue by KTamas** [trek10inc/awsume#136]
When I run `awsume -a`, it works, but it never terminates. According to the documentation, it spins up `autoawsume` in the background, which makes me assume that it should terminate and then just have `autoawsume` running in the background? It's kind of annoying to leave a terminal tab open just for `awsume`.

I'm using the latest version of `fish`.

If this is a feature and not a bug, then I'd like to request this as a feature :)

**Comment by mtskillman** [comment]
@KTamas apologies for the very long delay here but I'm unable to replicate this with awsume 4.5.3 and fish 3.6.1

note that there has been at least 1 relevant change, ebd19794957bceae9f19f28a9916f7b13aa12252, since you created this issue report. 

based upon the previously mentioned commit, it is possible that awsume was failing yet also not properly exiting, causing your shell to hang.
