### ISSUE TITLE
AWSume not setting AWS_PROFILE env variable on Mac

### ISSUE THREAD

**Issue by varun1231** [trek10inc/awsume#140]
Running awsume `profile-name` isn't setting environment variable `AWS_PROFILE` and therefore, I am unable to use it directly with terraform. I have to export that variable separately. It does however set `AWSUME_PROFILE`. Seen below are debug logs as I ran the last awsume with --debug flag.

<img width="975" alt="Screenshot 2021-03-29 at 13 17 28" src="https://user-images.githubusercontent.com/24938253/112835543-53789080-9091-11eb-96d3-8f944f0b0581.png">

And get the following error when trying to do `awsume -a`

<img width="974" alt="Screenshot 2021-03-29 at 13 22 42" src="https://user-images.githubusercontent.com/24938253/112836047-fcbf8680-9091-11eb-97ef-d960b9980bd5.png">

Note: Mac OSX version is Big Sur 11.2.3

**Comment by bdurrani** [comment]
I'm seeing the same issue. Using big sur 11.3 with awsume 4.5

**Comment by bdurrani** [comment]
Looks like I missed the step about setting up the alias. Once I added the alias, things started working
https://awsu.me/general/quickstart.html#alias-setup

**Comment by mbarneyjr** [comment]
Yep, the alias should be setup in order to allow awsume to modify your current shell's environment variables. We recently released 4.5.1, which improves the `awsume-configure` command so that if you run it without any flags (so just `awsume-configure`), it'll try to set everything up for each shell you have installed based on sane defaults, so this could be used to help setup awsume if the installation process doesn't work right

Closing for now, but if you still experience issues please reopen this issue or open a new one, thanks!

**Comment by Hobart2967** [comment]
+1, happens as of now. I ran "awsume profile" with everything set up correctly, still no AWS_PROFILE variable.
