### ISSUE TITLE
awsume <role_name> doesn't assume role

### ISSUE THREAD

**Issue by eddyaman** [trek10inc/awsume#52]
Hi,
I am trying to use awsume to assume a role, but it doesn't switch role when I input `awsume <role_name>`.
As a workaround, I have to input `awsume <role_name> -s` and then paste the output again.

Can you please help me on what am I doing wrong?

Thanks

**Comment by Vitiate** [comment]
Oddly enough I just had the same issue start yesterday. It used to work and in fact still works on some of my old shells that are still running. 

When I do a --debug I get to:

awsume.awsumepy.export_data : Exporting data to shell wrapper
 And there are no errors. 

Both a terminal that is working and a terminal that is not working have the same logs.

Its like it is not executing the exports depending on the terminal, but not generating any errors because of it..

**Comment by mbarneyjr** [comment]
Awsume relies on an alias to be set in order to function properly. This alias `source`'s awsume, so that when the awsume shell script exports the AWS environment variables, it applies to your current shell.

Ensure that you have an alias set up

Follow the troubleshooting guide for more info, and let me know if you get your issue resolved:

https://github.com/trek10inc/awsume/wiki/Troubleshooting

**Comment by Vitiate** [comment]
Thanks.. I was working my way there and almost had it. I guess I should not start poking around until I have has my coffee...

Great work btw, thank you so much for this script.
![image](https://user-images.githubusercontent.com/4108142/57536471-7b29a880-7301-11e9-8c60-d8df9ed0ec95.png)

**Comment by eddyaman** [comment]
hey @mbarneyjr , thanks for the help mate. It worked. 🎉 
I didn't realize that you have to setup the alias, because I never had to do that in windows.
Thanks again and awesome tool.
