### ISSUE TITLE
Environment variables are not exported when using fish shell

### ISSUE THREAD

**Issue by c-bandy** [trek10inc/awsume#71]
I've looked a bit at the code in `shell_scripts/awsume.fish` and it looks like the behavior described would export environment variables.

Could it be that `awsume.fish` does not get executed in my shell when I run `awsume`? A subshell running another shell (i.e. bash) would not `export` variables into fish due to the nature of `set`.

I could also be going about this completely wrong and fish simply needs special setup and I missed this in the documentation somewhere. But regardless I think it should work out of the box in any supported shell.

**Comment by mbarneyjr** [comment]
Awsume works on shells like bash and zsh by defining an alias in the login file for that shell. That alias `source`s the main awsume script, so that the environment variables set in the script are actually set in your current shell

Upon further reading, it appears you need something like https://github.com/edc/bass installed to have this functionality in fish

Beyond that, you must make sure that the alias is defined in your login file and actually set in your terminal for everything to work correctly

**Comment by c-bandy** [comment]
Yep - `bass source awsume` worked perfectly. Thanks!
