### ISSUE TITLE
multiple issues with awsume  

### ISSUE THREAD

**Issue by joelgrimberg** [trek10inc/awsume#89]
on a fresh machine, when I install awsume 4.1.10 with brew, typing 'awsume <tab' 
executes 'autocompletion' but I get 4x:
`awsume: error: unrecognized arguments: --rolesusers
usage: awsume [-h] [-v] [-r] [-s] [-u] [-a] [-k] [-l [more]]
              [--refresh-autocomplete] [--role-arn role_arn]
              [--principal-arn principal_arn] [--source-profile source_profile]
              [--external-id external_id] [--mfa-token mfa_token]
              [--region region] [--session-name session_name]
              [--role-duration role_duration]
              [--with-saml | --with-web-identity] [--json json]
              [--credentials-file credentials_file] [--config-file config_file]
              [--config [option [option ...]]] [--list-plugins] [--info]
              [--debug]
              [profile_name]`

when I type awsume <name_of_profile>, I just get another prompt but the profile did not load.

**Comment by mbarneyjr** [comment]
The availability of awsume on brew is not officially maintained by the team here.

The official recommendation is to install awsume via [pipx](https://pipxproject.github.io/pipx/)

However, the problem you're experiencing is likely to be an issue with an older (3.x or lower) autocomplete script still hanging around. You'll have to find out where that is (depends on how your shell handles autocomplete) and remove it. More information on upgrading [here](https://awsu.me/updating-v4/).

As for the second issue, this is likely because the awsume alias is not loaded. The alias should look like this: `alias awsume=". awsume"`. The alias is required because a subshell cannot alter a parent shell's environment variables. To add this alias to your shell's login files (and also add the autocomplete script), use the `awsume-configure` utility, more information found [here](https://awsu.me/utilities/awsume-configure.html).
